/*******************************************************************************************************
 *
 * RosMessageConverter.java, in gama.plugin.ros, is part of the source code of the GAMA modeling and simulation
 * platform.
 *
 * (c) 2007-2026 UMI 209 UMMISCO IRD/SU & Partners (IRIT, MIAT, ESPACE-DEV, CTU)
 *
 * Visit https://github.com/TANGO-projet/gama.plugin.ros for license information and contacts.
 *
 ********************************************************************************************************/
package gama.plugin.ros.utils;

import java.lang.reflect.Array;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeSet;
import java.util.concurrent.ConcurrentHashMap;

import gama.api.exceptions.GamaRuntimeException;
import gama.api.gaml.types.IType;
import gama.api.gaml.types.Types;
import gama.api.runtime.scope.IScope;
import gama.api.types.list.GamaListFactory;
import gama.api.types.list.IList;
import gama.api.types.map.GamaMapFactory;
import gama.api.types.map.IMap;
import us.ihmc.fastddsjava.cdr.idl.IDLObjectSequence;
import us.ihmc.fastddsjava.cdr.idl.IDLSequence;
import us.ihmc.fastddsjava.cdr.idl.IDLStringSequence;
import us.ihmc.jros2.ROS2Message;

/**
 * Converts jros2 messages to and from the GAMA maps and lists that the operators manipulate.
 *
 * <h3>Why reflection, and why it is not symmetric</h3>
 *
 * <p>
 * The message classes generated by jros2 are <b>not</b> Java beans. A scalar field such as {@code Vector3.x} does have
 * a {@code setX(double)}, but every compound field is exposed <b>read-only and mutated in place</b>: {@code Twist} only
 * declares {@code getLinear()} returning a live {@code Vector3}, {@code LaserScan} only declares {@code getRanges()}
 * returning a live {@code IDLFloatSequence}, and {@code PoseWithCovariance} only declares {@code getCovariance()}
 * returning a live {@code double[]}. Writing a message therefore cannot be a walk over setters. The write path here
 * looks for a setter first, and falls back to fetching the sub-object through its getter and filling it in place.
 * </p>
 *
 * <h3>Type mapping</h3>
 *
 * <table>
 * <caption>Correspondence between ROS field types and GAML types</caption>
 * <tr><td>ROS float32, float64</td><td>GAML {@code float}</td></tr>
 * <tr><td>ROS int8..int64, uint8..uint64</td><td>GAML {@code int}, a long out of int range being kept as is</td></tr>
 * <tr><td>ROS bool</td><td>GAML {@code bool}</td></tr>
 * <tr><td>ROS string</td><td>GAML {@code string}</td></tr>
 * <tr><td>nested message</td><td>GAML {@code map<string, unknown>}</td></tr>
 * <tr><td>sequence, fixed-size array</td><td>GAML {@code list}</td></tr>
 * </table>
 *
 * <p>
 * Reading is tolerant: whatever the message holds is returned. Writing is strict: a key matching no field of the
 * message raises a {@link GamaRuntimeException} listing the fields that do exist, because a typo in a field name would
 * otherwise publish a default-valued message and stay invisible.
 * </p>
 */
public final class RosMessageConverter {

	/** Per-class field descriptors, built once. Message classes never change, so the cache needs no invalidation. */
	private static final Map<Class<?>, Map<String, Accessor>> ACCESSORS = new ConcurrentHashMap<>();

	/**
	 * The two ways a field of a jros2 message can be written: through a setter, or by mutating in place the object
	 * returned by its getter.
	 *
	 * @param name
	 *            the GAML name of the field
	 * @param getter
	 *            the zero-argument getter, never null
	 * @param setter
	 *            the one-argument setter, or null when the field is only mutable in place
	 */
	private record Accessor(String name, Method getter, Method setter) {}

	private RosMessageConverter() {}

	// ---------------------------------------------------------------------------------------------------------------
	// Message -> GAMA map
	// ---------------------------------------------------------------------------------------------------------------

	/**
	 * Converts a message to a GAMA map keyed by field name.
	 *
	 * <p>
	 * Called from the DDS callback thread, so it deliberately takes no scope: it allocates plain GAMA containers and
	 * touches nothing else of the simulation.
	 * </p>
	 *
	 * @param msg
	 *            the message, may be null
	 * @return a map from field name to value, empty if the message is null
	 */
	public static IMap<String, Object> toGamaMap(final ROS2Message<?> msg) {
		final IMap<String, Object> result = GamaMapFactory.create(Types.STRING, Types.NO_TYPE);
		if (msg == null) return result;
		for (final Accessor accessor : accessorsOf(msg.getClass()).values()) {
			try {
				result.put(accessor.name(), toGamaValue(accessor.getter().invoke(msg)));
			} catch (final ReflectiveOperationException | RuntimeException e) {
				// a getter of a generated message class does not throw; if one ever does, that single field is left
				// out rather than the whole message being lost
			}
		}
		return result;
	}

	/**
	 * Converts one value read from a message to its GAML counterpart.
	 *
	 * @param value
	 *            the value returned by a getter
	 * @return the GAML value
	 */
	private static Object toGamaValue(final Object value) {
		return switch (value) {
			case null -> null;
			case final StringBuilder sb -> sb.toString();
			case final ROS2Message<?> nested -> toGamaMap(nested);
			case final Character c -> String.valueOf(c);
			case final Float f -> Double.valueOf(f.doubleValue());
			case final Double d -> d;
			case final Long l -> l.longValue() == l.intValue() ? Integer.valueOf(l.intValue()) : l;
			case final Byte b -> Integer.valueOf(b.intValue());
			case final Short s -> Integer.valueOf(s.intValue());
			case final Iterable<?> iterable -> toGamaList(iterable);
			default -> value.getClass().isArray() ? arrayToGamaList(value) : value;
		};
	}

	/**
	 * Converts an IDL sequence, or any other iterable, to a GAML list.
	 *
	 * @param iterable
	 *            the iterable
	 * @return the list
	 */
	private static IList<Object> toGamaList(final Iterable<?> iterable) {
		final List<Object> items = new ArrayList<>();
		for (final Object item : iterable) { items.add(toGamaValue(item)); }
		return GamaListFactory.wrap(contentTypeOf(items), items);
	}

	/**
	 * Converts a fixed-size array field, such as the 36 covariance values of a pose, to a GAML list.
	 *
	 * @param array
	 *            the array, of any component type including primitives
	 * @return the list
	 */
	private static IList<Object> arrayToGamaList(final Object array) {
		final int length = Array.getLength(array);
		final List<Object> items = new ArrayList<>(length);
		for (int i = 0; i < length; i++) { items.add(toGamaValue(Array.get(array, i))); }
		return GamaListFactory.wrap(contentTypeOf(items), items);
	}

	/**
	 * Infers the content type of a list from its first element, so that models get {@code list<float>} rather than
	 * {@code list<unknown>}.
	 *
	 * @param items
	 *            the converted items
	 * @return the content type
	 */
	private static IType<?> contentTypeOf(final List<Object> items) {
		if (items.isEmpty()) return Types.NO_TYPE;
		return switch (items.get(0)) {
			case final Double d -> Types.FLOAT;
			case final Integer i -> Types.INT;
			case final Boolean b -> Types.BOOL;
			case final String s -> Types.STRING;
			case final IMap<?, ?> m -> Types.MAP;
			case final IList<?> l -> Types.LIST;
			case null, default -> Types.NO_TYPE;
		};
	}

	// ---------------------------------------------------------------------------------------------------------------
	// GAMA map -> message
	// ---------------------------------------------------------------------------------------------------------------

	/**
	 * Fills a message in place from a GAMA map. Fields absent from the map keep the value they already have, which for
	 * a freshly allocated message is the ROS default.
	 *
	 * @param scope
	 *            the scope, used to report errors
	 * @param msg
	 *            the message to fill
	 * @param data
	 *            the map, may be null in which case nothing is written
	 */
	public static void fromGamaMap(final IScope scope, final ROS2Message<?> msg, final Map<String, Object> data) {
		if (msg == null || data == null) return;
		final Map<String, Accessor> accessors = accessorsOf(msg.getClass());
		for (final Map.Entry<String, Object> entry : data.entrySet()) {
			final String key = entry.getKey();
			final Accessor accessor = accessors.get(key);
			if (accessor == null) throw GamaRuntimeException.error("'" + key + "' is not a field of the ROS2 message "
					+ msg.getClass().getName() + ". Its fields are " + new TreeSet<>(accessors.keySet()) + ".", scope);
			write(scope, msg, accessor, entry.getValue(), key);
		}
	}

	/**
	 * Writes one field, through its setter when it has one and in place otherwise.
	 *
	 * @param scope
	 *            the scope
	 * @param msg
	 *            the message being filled
	 * @param accessor
	 *            the field
	 * @param value
	 *            the GAML value
	 * @param path
	 *            the field name, used in error messages
	 */
	private static void write(final IScope scope, final ROS2Message<?> msg, final Accessor accessor,
			final Object value, final String path) {
		try {
			if (accessor.setter() != null) {
				final Class<?> expected = accessor.setter().getParameterTypes()[0];
				accessor.setter().invoke(msg, coerce(scope, value, expected, path));
				return;
			}
			// no setter: the field is a compound one, mutated through the object its getter returns
			final Object target = accessor.getter().invoke(msg);
			if (target == null) throw GamaRuntimeException
					.error("The field '" + path + "' of " + msg.getClass().getName() + " cannot be written", scope);
			writeInPlace(scope, target, value, path);
		} catch (final GamaRuntimeException e) {
			throw e;
		} catch (final ReflectiveOperationException | RuntimeException e) {
			throw GamaRuntimeException.error(
					"Cannot write the field '" + path + "' of " + msg.getClass().getName() + ": " + e.getMessage(),
					scope);
		}
	}

	/**
	 * Fills in place the live object held by a message: a sub-message, an IDL sequence, a fixed-size array or a string
	 * buffer.
	 *
	 * @param scope
	 *            the scope
	 * @param target
	 *            the live object
	 * @param value
	 *            the GAML value
	 * @param path
	 *            the field name, used in error messages
	 */
	@SuppressWarnings ("unchecked")
	private static void writeInPlace(final IScope scope, final Object target, final Object value, final String path) {
		switch (target) {
			case final ROS2Message<?> sub -> {
				if (!(value instanceof Map)) throw typeError(scope, path, "a map", value);
				fromGamaMap(scope, sub, (Map<String, Object>) value);
			}
			case final StringBuilder sb -> {
				sb.setLength(0);
				sb.append(value == null ? "" : value.toString());
			}
			case final IDLSequence<?> seq -> fillSequence(scope, seq, asList(scope, value, path), path);
			default -> {
				if (!target.getClass().isArray()) throw GamaRuntimeException.error(
						"The field '" + path + "' has the unsupported type " + target.getClass().getName(), scope);
				fillArray(scope, target, asList(scope, value, path), path);
			}
		}
	}

	/**
	 * Replaces the content of an IDL sequence by the elements of a list.
	 *
	 * @param scope
	 *            the scope
	 * @param sequence
	 *            the live sequence
	 * @param values
	 *            the GAML values
	 * @param path
	 *            the field name, used in error messages
	 */
	@SuppressWarnings ({ "unchecked", "rawtypes" })
	private static void fillSequence(final IScope scope, final IDLSequence<?> sequence, final List<?> values,
			final String path) {
		if (!sequence.isUnbounded() && values.size() > sequence.getMaxSize())
			throw GamaRuntimeException.error("The field '" + path + "' holds at most " + sequence.getMaxSize()
					+ " elements, " + values.size() + " given", scope);
		sequence.clear();
		switch (sequence) {
			case final IDLObjectSequence objects -> {
				for (int i = 0; i < values.size(); i++) {
					writeInPlace(scope, objects.add(), values.get(i), path + "[" + i + "]");
				}
			}
			case final IDLStringSequence strings -> {
				for (final Object item : values) { strings.add(item == null ? "" : item.toString()); }
			}
			// every primitive sequence (IDLFloatSequence, IDLIntSequence, ...) declares add(<primitive>)
			default -> {
				final Method add = singleArgumentAdd(sequence.getClass());
				if (add == null) throw GamaRuntimeException.error("The field '" + path
						+ "' has the unsupported sequence type " + sequence.getClass().getName(), scope);
				final Class<?> element = add.getParameterTypes()[0];
				try {
					for (int i = 0; i < values.size(); i++) {
						add.invoke(sequence, coerce(scope, values.get(i), element, path + "[" + i + "]"));
					}
				} catch (final ReflectiveOperationException e) {
					throw GamaRuntimeException.error("Cannot fill the field '" + path + "': " + e.getMessage(), scope);
				}
			}
		}
	}

	/**
	 * Overwrites a fixed-size array field. The list must have exactly the length of the array, since ROS gives these
	 * fields a fixed cardinality: 36 for a covariance matrix, 9 for an inertia matrix, and so on.
	 *
	 * @param scope
	 *            the scope
	 * @param array
	 *            the live array
	 * @param values
	 *            the GAML values
	 * @param path
	 *            the field name, used in error messages
	 */
	private static void fillArray(final IScope scope, final Object array, final List<?> values, final String path) {
		final int length = Array.getLength(array);
		if (values.size() != length) throw GamaRuntimeException.error("The field '" + path + "' holds exactly " + length
				+ " elements, " + values.size() + " given", scope);
		final Class<?> component = array.getClass().getComponentType();
		for (int i = 0; i < length; i++) {
			Array.set(array, i, coerce(scope, values.get(i), component, path + "[" + i + "]"));
		}
	}

	/**
	 * Converts a GAML value to the Java type a setter expects.
	 *
	 * @param scope
	 *            the scope
	 * @param value
	 *            the GAML value
	 * @param target
	 *            the expected type, possibly primitive
	 * @param path
	 *            the field name, used in error messages
	 * @return the coerced value
	 */
	private static Object coerce(final IScope scope, final Object value, final Class<?> target, final String path) {
		if (value == null) {
			if (target.isPrimitive()) throw typeError(scope, path, "a " + target.getName(), null);
			return null;
		}
		if (target == String.class) return value.toString();
		if (target == StringBuilder.class) return new StringBuilder(value.toString());
		if (target == boolean.class || target == Boolean.class) {
			if (value instanceof final Boolean b) return b;
			throw typeError(scope, path, "a bool", value);
		}
		if (target == char.class || target == Character.class) {
			final String text = value.toString();
			if (text.length() != 1) throw typeError(scope, path, "a one-character string", value);
			return text.charAt(0);
		}
		if (value instanceof final Number number) {
			if (target == double.class || target == Double.class) return number.doubleValue();
			if (target == float.class || target == Float.class) return number.floatValue();
			if (target == int.class || target == Integer.class) return number.intValue();
			if (target == long.class || target == Long.class) return number.longValue();
			if (target == short.class || target == Short.class) return number.shortValue();
			if (target == byte.class || target == Byte.class) return number.byteValue();
		}
		if (target.isInstance(value)) return value;
		throw typeError(scope, path, "a " + target.getSimpleName(), value);
	}

	/**
	 * Checks that a value is a list before it is used to fill a sequence or an array.
	 *
	 * @param scope
	 *            the scope
	 * @param value
	 *            the GAML value
	 * @param path
	 *            the field name, used in error messages
	 * @return the value as a list
	 */
	private static List<?> asList(final IScope scope, final Object value, final String path) {
		if (value instanceof final List<?> list) return list;
		throw typeError(scope, path, "a list", value);
	}

	/**
	 * Builds the exception raised when a GAML value does not fit the field it is assigned to.
	 *
	 * @param scope
	 *            the scope
	 * @param path
	 *            the field name
	 * @param expected
	 *            a human-readable description of what was expected
	 * @param value
	 *            the offending value
	 * @return the exception, to be thrown by the caller
	 */
	private static GamaRuntimeException typeError(final IScope scope, final String path, final String expected,
			final Object value) {
		return GamaRuntimeException.error("The field '" + path + "' expects " + expected + ", but got "
				+ (value == null ? "nil" : value + " (" + value.getClass().getSimpleName() + ")"), scope);
	}

	// ---------------------------------------------------------------------------------------------------------------
	// Reflection
	// ---------------------------------------------------------------------------------------------------------------

	/**
	 * Returns the fields of a message class, indexed by their GAML name.
	 *
	 * @param messageClass
	 *            the class of a generated jros2 message
	 * @return the fields, never null
	 */
	private static Map<String, Accessor> accessorsOf(final Class<?> messageClass) {
		return ACCESSORS.computeIfAbsent(messageClass, RosMessageConverter::buildAccessors);
	}

	/**
	 * Lists the field names of a message class, for documentation and error messages.
	 *
	 * @param messageClass
	 *            the class of a generated jros2 message
	 * @return the field names, sorted
	 */
	public static IList<String> fieldsOf(final Class<?> messageClass) {
		return GamaListFactory.wrap(Types.STRING, new ArrayList<>(new TreeSet<>(accessorsOf(messageClass).keySet())));
	}

	/**
	 * Pairs the getters and setters of a message class.
	 *
	 * <p>
	 * {@code getXxxAsString()} is skipped: jros2 generates it next to the {@code getXxx()} returning a
	 * {@code StringBuilder}, and keeping both would put the same string under two keys.
	 * </p>
	 *
	 * @param messageClass
	 *            the class of a generated jros2 message
	 * @return the fields indexed by GAML name
	 */
	private static Map<String, Accessor> buildAccessors(final Class<?> messageClass) {
		final Map<String, Method> setters = new HashMap<>();
		final Map<String, Method> getters = new LinkedHashMap<>();
		for (final Method m : messageClass.getMethods()) {
			if (Modifier.isStatic(m.getModifiers()) || m.getDeclaringClass() == Object.class) { continue; }
			final String name = m.getName();
			if (name.startsWith("get") && name.length() > 3 && m.getParameterCount() == 0
					&& m.getReturnType() != void.class && !name.endsWith("AsString")) {
				getters.put(decapitalize(name.substring(3)), m);
			} else if (name.startsWith("set") && name.length() > 3 && m.getParameterCount() == 1) {
				setters.put(decapitalize(name.substring(3)), m);
			}
		}
		final Map<String, Accessor> result = new LinkedHashMap<>();
		getters.forEach((name, getter) -> result.put(name, new Accessor(name, getter, setters.get(name))));
		return Map.copyOf(result);
	}

	/**
	 * Finds the {@code add(<primitive>)} method of a primitive IDL sequence.
	 *
	 * @param sequenceClass
	 *            the sequence class
	 * @return the method, or null if the class does not declare one
	 */
	private static Method singleArgumentAdd(final Class<?> sequenceClass) {
		for (final Method m : sequenceClass.getMethods()) {
			if ("add".equals(m.getName()) && m.getParameterCount() == 1) return m;
		}
		return null;
	}

	/**
	 * Turns the tail of an accessor name into a field name: {@code "AngleMin"} becomes {@code "angleMin"}.
	 *
	 * @param name
	 *            the tail of the accessor name
	 * @return the field name
	 */
	private static String decapitalize(final String name) {
		return Character.toLowerCase(name.charAt(0)) + name.substring(1);
	}

	/**
	 * Allocates a message of the given class.
	 *
	 * @param scope
	 *            the scope
	 * @param messageClass
	 *            the class of a generated jros2 message
	 * @return a new message, with every field at its ROS default
	 */
	@SuppressWarnings ({ "unchecked", "rawtypes" })
	public static ROS2Message<?> newInstance(final IScope scope, final Class<?> messageClass) {
		try {
			return ROS2Message.createInstance((Class) messageClass);
		} catch (final RuntimeException e) {
			throw GamaRuntimeException.error(
					"Cannot instantiate the ROS2 message " + messageClass.getName() + ": " + e.getMessage(), scope);
		}
	}

}
